Here's an AIM Austin special: linear algebra in Python, in Jupyter, done last minute by someone who
1. Doesn't know any python
2. Had three beers with dinner
3. But fortunately has internet access

Let's start by loading some of the standard Python libraries.

In [1]:
from sympy import *
init_printing()
import numpy as np

Sympy is a useful Python library for symbolic manipulation. If you're using Python notebooks, it's pretty much guaranteed that Sympy will appear in your Calculus and Linear Algebra notebooks. 

There is good [documentation](http://docs.sympy.org/latest/tutorial/calculus.html) for calculus in Sympy.

It's relatively user-friendly, but it really shines in Jupyter, where rendering is done using MathJax. Here are [some more Sympy examples in Jupyter](http://nbviewer.jupyter.org/url/www.inp.nsk.su/~grozin/python/sympy.ipynb).

Numpy is a numerical library, useful for things like handling values in vectors and matrices. Again, there is plenty of [useful documentation on the internet](http://rlhick.people.wm.edu/stories/linear-algebra-python-basics.html)

Defining matrices in Numpy is straighforward. Let's define the matrices 

$$A = \begin{bmatrix} 1&2\\3&4\end{bmatrix} \text{ and } B = \begin{bmatrix} 6&-3\\-2&1\end{bmatrix}$$

In [2]:
A = np.matrix(
    [[1,2],[3,4]])
B = np.matrix(
    [[6,-3],[-2,1]])

Let's have Jupyter display one of our matrices. 

In [3]:
print(A)

[[1 2]
 [3 4]]


That's OK for display in Python, but less so in Jupyter. Here's a matrix entered using Sympy in Jupyter.

In [4]:
from sympy.interactive.printing import init_printing
init_printing(use_unicode=False, wrap_line=False, no_global=True)
from sympy.matrices import Matrix, eye, zeros, ones, diag, GramSchmidt
M=Matrix([[1,2,3],[4,5,6]]);
M

[1  2  3]
[       ]
[4  5  6]

Now that we've got our matrices in place, we can easily add and multiply them.

In [5]:
A+B

matrix([[ 7, -1],
        [ 1,  5]])

In [6]:
A*B

matrix([[ 2, -1],
        [10, -5]])

Now let's solve the system
$$
\begin{array}{ccccc}
x&+&2y&=&2\\
3x&+&4y&=&3
\end{array}$$
by realizing it as the matrix equation $\begin{bmatrix}1&2\\3&4\end{bmatrix}\begin{bmatrix}x\\y\end{bmatrix}=\begin{bmatrix}2\\1\end{bmatrix}$

In [7]:
C=np.matrix([[2],[3]])
X=np.linalg.solve(A,B)
print(X)

[[-14.   7.]
 [ 10.  -5.]]


What else can we do? There's some basic documentation on the [plot.ly website](https://plot.ly/python/linear-algebra/). For example, we can do determinants and inverses.

In [8]:
det=np.linalg.det(A)
inv=np.linalg.inv(A)

In [9]:
det

In [10]:
inv

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [11]:
ev = np.linalg.eigvals(A)
ev

array([-0.37228132,  5.37228132])

Pressed for time? Someone has done Jupyter notebooks for all of Gilbert Strang's Linear Algebra, and [released it as MIT Open Courseware](https://github.com/juanklopper/MIT_OCW_Linear_Algebra_18_06)!

Dealing with advanced students? How about an entire Juptyer [textbook on numerical linear algebra](https://github.com/fastai/numerical-linear-algebra)?